name: Server Simulator

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]
    workflow_dispatch:

env:
    CARGO_TERM_COLOR: always

jobs:
    build-matrix:
        name: Build matrix
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.build-matrix-step.outputs.matrix }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: dtolnay/rust-toolchain@stable

            - name: Build matrix JSON
              id: build-matrix-step
              run: |
                  cargo install --git https://github.com/MoosicBox/MoosicBox clippier
                  MATRIX=$(
                      clippier \
                          features \
                          server \
                          -o json \
                          --features default \
                          | jq -rc \
                              '[
                                  .[]
                                  | {
                                      "name": (.name | sub("^dst_demo_"; "")),
                                      "path": (.path),
                                      "features": (.features),
                                      "requiredFeatures": (if .requiredFeatures != null then .requiredFeatures | join(",") else null end),
                                      "os": (.os + "-latest"),
                                      "env": (.env)
                                  }
                                  | del(.requiredFeatures | nulls)
                                  | del(.env | nulls)
                              ]'
                  )
                  echo "Using matrix (raw):"
                  echo $MATRIX
                  echo "Using matrix:"
                  echo $MATRIX | jq
                  echo 'matrix<<EOF' >> $GITHUB_OUTPUT
                  echo $MATRIX >> $GITHUB_OUTPUT
                  echo 'EOF' >> $GITHUB_OUTPUT

    simulator:
        name: Simulator

        runs-on: ${{ matrix.package.os }}

        needs: build-matrix

        strategy:
            fail-fast: false

            matrix:
                package: ${{ fromJson(needs.build-matrix.outputs.matrix) }}

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: dtolnay/rust-toolchain@stable

            - name: Run server simulator
              shell: bash
              env:
                  NO_TUI: 1
                  SIMULATOR_DURATION: 10
                  SIMULATOR_RUNS: 30
                  RUST_LOG: ${{ runner.debug && 'trace' || 'debug' }}
              run: |
                  while read -r feature; do \
                      ${{ matrix.package.env }} cargo run --release -p dst_demo_server_simulator ${{ runner.debug && '-vv' }} \
                          --no-default-features \
                          --features="fail-on-warnings,$feature" ${{ matrix.package.cargo }}
                  done <<<"$(echo '${{ toJson(matrix.package.features) }}' | jq -r '.[]')"
